buildscript {
	repositories {
		maven { url "https://repo.grails.org/grails/core" }
	}
	dependencies {
		classpath "org.apache.grails:grails-gradle-plugins:$grailsGradlePluginVersion"
		classpath "org.apache.grails:grails-data-hibernate5:${project.'gorm.version' - ".RELEASE"}"
	}
}

plugins {
	id "groovy"
	id "org.apache.grails.gradle.grails-web"
	id "org.apache.grails.gradle.grails-gsp"
	id "war"
	id "idea"
	// Not needed because no /assets directory
	// id "com.bertramlabs.asset-pipeline" version "${assetPipelineVersion}"
	id "eclipse"
}

version "0.1"
group "alternativeconfig"

dependencies {
	implementation project(':build-test-data')

	profile("org.apache.grails.profiles:web")

	implementation("org.apache.grails:grails-core")
	implementation("org.apache.grails:grails-logging")
	implementation("org.apache.grails:grails-databinding")
	implementation("org.apache.grails:grails-i18n")
	implementation("org.apache.grails:grails-interceptors")
	implementation("org.apache.grails:grails-rest-transforms")
	implementation("org.apache.grails:grails-services")
	implementation("org.apache.grails:grails-url-mappings")
	implementation("org.apache.grails:grails-web-boot")
	implementation("org.apache.grails:grails-gsp")
	implementation("org.apache.grails:grails-data-hibernate5")
	implementation("org.apache.grails:grails-scaffolding")
	implementation("org.apache.grails:grails-sitemesh3")
	implementation("org.springframework.boot:spring-boot-autoconfigure")
	implementation("org.springframework.boot:spring-boot-starter")
	implementation("org.springframework.boot:spring-boot-starter-actuator")
	implementation("org.springframework.boot:spring-boot-starter-logging")
	implementation("org.springframework.boot:spring-boot-starter-tomcat")
	implementation("org.springframework.boot:spring-boot-starter-validation")

	console("org.grails:grails-console")

	runtimeOnly("com.bertramlabs.plugins:asset-pipeline-grails")
	runtimeOnly("com.h2database:h2")
	runtimeOnly("org.apache.tomcat:tomcat-jdbc")
	runtimeOnly("org.fusesource.jansi:jansi")

	integrationTestImplementation testFixtures("org.apache.grails:grails-geb")

	testImplementation("org.apache.grails:grails-testing-support-datamapping")
	testImplementation("org.apache.grails:grails-testing-support-web")
	testImplementation("org.spockframework:spock-core")
}

// No assets in test project
//assets {
//	minifyJs = true
//	minifyCss = true
//}