[[upgrading]]
== Upgrading
When upgrading from older versions of Grails, first follow the standard Grails upgrade process.

=== Upgrading to 7.0
Build Test Data 7.0 requires Grails 8. Grails 8 also changes the default nullability of domain properties, see <<installation>> for how this affects Build Test Data.

==== BuildDataTest Renamed
The `BuildDataTest` trait has been renamed to `BuildDataUnitTest` to make it clear that it is only meant for unit tests. Integration tests should continue to implement `TestDataBuilder`.

`BuildDataTest` remains as a deprecated alias of `BuildDataUnitTest` and will be removed in a future release. Update the import and trait name in your unit tests:

```groovy
import grails.buildtestdata.BuildDataUnitTest

class AuthorSpec extends Specification implements BuildDataUnitTest {
    ...
}
```

==== Values That Can't Be Bound Fail the Build
Previously, a value passed to `build()` that could not be converted to its property's type, such as `'abc'` for an `Integer` property or a name that isn't one of an enum's constants, was silently skipped and the property was left `null`. `build()` now throws an `IllegalArgumentException` listing every value that could not be bound. This also applies to the `sampleData` values in `TestDataConfig.groovy`.

Values for properties that don't exist on the class are still ignored, but are now logged as a warning.

To ease migrating existing tests, set `failOnBindingError` to `false` in `TestDataConfig.groovy` to restore the previous behavior. The values that could not be bound are then skipped and logged as a warning instead of failing the build. See <<testdataconfig>>.

```groovy
testDataConfig {
    failOnBindingError = false
}
```

==== UnitTestDataBuilder Removed
The deprecated `UnitTestDataBuilder` trait has been removed. Implement `BuildDataUnitTest` instead.

=== Upgrading to 3.3

==== Performance Improvements
The core plugin has been refactored to reduce metaClass dependency and remove a few poor performing contructs (I'm looking at you ClassPathScanningCandidateComponentProvider).

Most of the plugin classes have also been converted to `@CompileStatic`. In addition, the DomainInstanceBuilder can be cached and re-used to prevent additional overhead.

==== Abstract Classes
Concrete subclasses are no longer discovered automatically. If you graph needs to build an abstract class, use the `abstractDefaults` parameter in `TestDataConfig` to specify a concrete subclass.

```groovy
abstractDefault = [
    'test.AbstractBook'   : MyBook,
    'test.AbstractAuthor' : Tolkien
]
```

==== Config Parameters
Some test data config parameters such as `abstractDefault` and `sampleData` used to allow either a Class or String as the map key.

In 3.3 and later, only a full package name String is allowed.

==== Disabling Via TestDataConfig
You can no longer disable via the `testDataConfig.enabled = false` option.

==== Build methods refactored
They all go through static helpers in the TestData eventually
`buildLazy` -> `findOrBuild` or `build(find:true)`
`buildWithoutSave` -> `build(save: false)`

==== Unit Tests
Most of the work when upgrading to Grails 3.3.x will involve refactoring related to the framework itself with only minor changes for build-test-data.

---
```groovy
@Build([Author])
class AuthorSpec extends Specification {
    ...
}
```

Just add the trait:
```groovy
@Build([Author])
class AuthorSpec extends Specification implements BuildDataUnitTest {
    ...
}
```

Optionally, use the standard Grails mock method:

```groovy
class AuthorSpec extends Specification implements BuildDataUnitTest {
    void setupSpec() {
        mockDomains(Author)
    }
    ...
}
```

or by overriding the *getDomainClassesToMock* method:

```groovy
class AuthorSpec extends Specification implements BuildDataUnitTest {
    Class[] getDomainClassesToMock() {
        [Author]
    }
    ...
}
```

or use with the BuildDomainTest and generics
```groovy
class AuthorSpec extends Specification implements BuildDomainTest<Author>{
    ...
}
```

WARNING: Make sure you use *DomainUnitTest* for unit tests and *TestDataBuilder* for integration tests.

==== Integration Tests
For integration tests, follow the standard Grails upgrade instructions and then add the `TestDataBuilder` trait:

```groovy
@Integration
@Rollback
class AuthorIntegrationSpec extends Specification implements TestDataBuilder {
    ...
}
```

