buildscript {
	repositories {
		maven { url "https://repo.grails.org/grails/core" }
	}
	dependencies {
		classpath "org.apache.grails:grails-gradle-plugins:$grailsGradlePluginVersion"
	}
}

group "org.grails.plugins"
apply plugin: "eclipse"
apply plugin: "idea"
apply plugin: "org.apache.grails.gradle.grails-plugin"

dependencies {
	implementation "org.springframework.boot:spring-boot-starter-logging"
	implementation "org.springframework.boot:spring-boot-autoconfigure"
	implementation "dk.brics:automaton:1.12-4"

	implementation "org.apache.grails:grails-core"
	implementation "org.apache.grails:grails-testing-support-datamapping"
	implementation "org.apache.grails:grails-databinding"
	implementation "org.apache.grails.data:grails-datastore-core"
	implementation "org.apache.grails:grails-console"

	// So we can run 'grails' and/or 'grails test-app' inside build-test-data
	profile "org.apache.grails.profiles:web-plugin"

	implementation "org.springframework.boot:spring-boot-starter-actuator"
	implementation "org.springframework.boot:spring-boot-starter-tomcat"
	implementation "org.apache.grails:grails-web-boot"

	runtimeOnly 'org.apache.groovy:groovy-dateutil'

	testImplementation "org.apache.grails:grails-data-hibernate5"
	testImplementation "com.h2database:h2"
	testImplementation "org.apache.tomcat:tomcat-jdbc"

	testImplementation "org.apache.grails:grails-testing-support-datamapping"
	testImplementation "org.apache.grails:grails-testing-support-web"
}

// Enable if you wish to package this plugin as a standalone application
bootJar.enabled = false

//this makes the groovy docs much more readable by shorting packages and providing links
groovydoc {
	excludes = ['**/*GrailsPlugin.groovy', '**/Application.groovy']
	link('https://docs.oracle.com/en/java/javase/17/docs/api', 'java.', 'org.xml', 'org.xml.')
	link('https://jakarta.ee/specifications/platform/9/apidocs', 'jakarta.')
	link("https://docs.spring.io/spring/docs/6.1.x/javadoc-api", 'org.springframework')
	link('https://docs.groovy-lang.org/4.0.24/html/gapi', 'groovy.', 'org.apache.groovy.')
	link('https://docs.grails.org/7.0.0/api', 'grails.', 'org.grails.')
	link('https://testing.grails.org/latest/api', 'grails.testing.', 'org.grails.testing.')
	link('http://gorm.grails.org/9.0.x/hibernate/api/', 'grails.gorm', 'grails.orm', 'org.grails.datastore', 'org.grails.orm')
}