plugins {
    id 'org.apache.grails.gradle.grails-plugin'
}

group 'io.github.longwa'

dependencies {
    implementation platform("org.apache.grails:grails-bom:$grailsVersion")
	implementation "dk.brics:automaton:1.12-4"

    // Use compileOnly for dependencies that are provided by the Grails runtime to allow us to depend on a grails snapshot and
    // and not have any users of this library use a snapshot dependency
	compileOnly "org.apache.grails:grails-core"
    compileOnly "org.apache.grails:grails-testing-support-datamapping"
    compileOnly "org.apache.grails.databinding:grails-databinding-core"
    compileOnly "org.apache.grails.data:grails-datamapping-core"
    compileOnly "org.apache.grails:grails-web-boot"

	runtimeOnly 'org.apache.groovy:groovy-dateutil'

	testImplementation "org.apache.grails:grails-data-hibernate5"
	testImplementation "com.h2database:h2"
	testImplementation "org.apache.tomcat:tomcat-jdbc"

	testImplementation "org.apache.grails:grails-testing-support-datamapping"
	testImplementation "org.apache.grails:grails-testing-support-web"
}

grails {
    springDependencyManagement = false
}

//this makes the groovy docs much more readable by shorting packages and providing links
groovydoc {
	excludes = ['**/*GrailsPlugin.groovy', '**/Application.groovy']
	link('https://docs.oracle.com/en/java/javase/17/docs/api', 'java.', 'org.xml', 'org.xml.')
	link('https://jakarta.ee/specifications/platform/9/apidocs', 'jakarta.')
	link("https://docs.spring.io/spring/docs/6.1.x/javadoc-api", 'org.springframework')
	link('https://docs.groovy-lang.org/4.0.24/html/gapi', 'groovy.', 'org.apache.groovy.')
	link('https://docs.grails.org/7.0.0/api', 'grails.', 'org.grails.')
	link('https://testing.grails.org/latest/api', 'grails.testing.', 'org.grails.testing.')
	link('http://gorm.grails.org/9.0.x/hibernate/api/', 'grails.gorm', 'grails.orm', 'org.grails.datastore', 'org.grails.orm')
}