plugins {
    id 'org.apache.grails.gradle.grails-plugin'
}

group = 'io.github.longwa'

dependencies {
    implementation "dk.brics:automaton:1.12-4"

    // Use compileOnly for dependencies that are provided by the Grails runtime to allow us to depend on a grails snapshot and
    // and not have any users of this library use a snapshot dependency
    compileOnly platform("org.apache.grails:grails-bom:$grailsVersion")
    compileOnly "org.apache.grails:grails-core"
    compileOnly "org.apache.grails:grails-testing-support-datamapping"
    compileOnly "org.apache.grails.databinding:grails-databinding-core"
    compileOnly "org.apache.grails.data:grails-datamapping-core"
    compileOnly "org.apache.grails:grails-web-boot"

	runtimeOnly 'org.apache.groovy:groovy-dateutil:5.1.3'

    testImplementation platform("org.apache.grails:grails-bom:$grailsVersion")
	testImplementation "org.apache.grails:grails-data-hibernate5"
	testImplementation "com.h2database:h2"
	testImplementation "org.apache.tomcat:tomcat-jdbc"
	testImplementation "org.apache.grails:grails-testing-support-datamapping"
	testImplementation "org.apache.grails:grails-testing-support-web"
}

grails {
    // Do not apply the grails-bom as a platform so it is not added to the published pom
    bom = null
}

//this makes the groovy docs much more readable by shorting packages and providing links
groovydoc {
	excludes = ['**/*GrailsPlugin.groovy', '**/Application.groovy']
	link('https://docs.oracle.com/en/java/javase/21/docs/api', 'java.', 'org.xml', 'org.xml.')
	link('https://jakarta.ee/specifications/platform/11/apidocs', 'jakarta.')
	link('https://docs.spring.io/spring-framework/docs/7.0.x/javadoc-api', 'org.springframework')
	link('https://docs.groovy-lang.org/5.1.3/html/gapi', 'groovy.', 'org.apache.groovy.')
	link("https://grails.apache.org/docs/${grailsVersion}/api", 'grails.', 'org.grails.')
}