file('../gradle.properties').withInputStream {
    Properties props = new Properties()
    props.load(it)
    project.ext.gradleProperties = props
}

repositories {
    maven { url "https://repo.grails.org/grails/restricted" }
    maven {
        url = 'https://central.sonatype.com/repository/maven-snapshots'
        content {
            includeVersionByRegex('cloud[.]wondrify', '.*', '.*-SNAPSHOT')
        }
    }
    maven {
        url = 'https://repository.apache.org/content/groups/snapshots'
        content {
            includeVersionByRegex 'org[.]apache[.]((grails)|(groovy)).*', '.*', '.*-SNAPSHOT'
        }
    }
}

dependencies {
    implementation platform("org.apache.grails:grails-bom:${gradleProperties.grailsVersion}")
    implementation "org.apache.grails:grails-gradle-plugins"
    implementation "cloud.wondrify:asset-pipeline-gradle"
}