[[introduction]]
== Introduction
Creating maintainable test data is hard. Often an entire object graph needs to be created to support the instantiation of a single domain object. This leads to either the cutting and pasting of that creation code, or relying on a canned set of objects that we've grown over time and maintained as the domain objects change. After a while, adding just one more widget to that set of canned data ends up breaking tests just about every time.

There has to be a better solution, right?

Yep! Due to the power and the glory of Grails, we have a lot of metadata at our fingertips about those domain objects. We know what constraints we've placed on our objects, and which objects depend on other objects to live.

Using this additional information, we've created a grails plugin that makes it easy to just provide those values that you want to exercise under test and not worry about the rest of the object graph that you need to create just to instantiate your domain objects.

Once installed, all you have to do is call the new "build" method on your domain class and you'll be given a valid instance with all of the required constraints given values.

```groovy
def author = Author.build(name: 'Ted Naleid')
//or
def author = TestData.build(Author, name: 'Ted Naleid')
```

=== Release History
* January 6th, 2018 - 3.3.0.RC1
** Support for Grails 3.3.x
** Major cleanup and performance improvements
** Trait based API
* May 7th, 2018 - 3.3.0
** Official release
** Minor bug fixes from release candidate
* June 1st, 2018 - 3.3.1
** Support building of any nested `Validateable`
** Fix misc data binding issues
** Fix build issues with Basic to-many collections
** Add 2nd `obj` parameter to TestDataConfig closures
** Other minor bug fixes and cleanup




